### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by anaclumos** [wwdc/2018#366]
First of all, Thank you for creating this repository. I benefited a lot from last year's submission, and would also like to help others as well.

For this year's submission, I have downloaded almost every project in this repository and tested them out. This dataset made me better understand what Apple wanted, and how I should work on my project. While comparing each project, I had some instances that I need to find a specific project again for reference. However, I wasn't able to find out specific playgrounds efficiently, since there was only "name" and some tech stacks here. And apparently, I just remembered the title or the context of the project and had hard times finding it back.

So this is my suggestion. Please make "Info" column here starting from next year. Merging Videos and Sources next to the title would also save more space. So this is what I think it should be.

The template is like the following.

```
| Name | <strong> Title </strong> <br> Description <br> <sub> Links, Tech stacks </sub> | Status |
```

It renders like the following.

| Name | Info | Status |
|-------|-----|-------|
|[Aaron Cheung](https://www.facebook.com/WahYanAaron) | <strong>Hong Kong</strong><br> PlaygroundBook introducing Hong Kong<br><sub>[YouTube](https://youtu.be/t9Bp4rkPh7E). UIKit, AVFoundation, Gesture Recognizer.</sub>| Rejected |
|[Aaron Nguyen](https://github.com/attwelveDev)|<strong>Guess The Emoji!</strong><br>Game guessing Emojis behind the  silhouette<br><sub>[GitHub](https://github.com/attwelveDev/WWDC18-Submission). UIKit, AVFoundation.</sub>| Rejected |
|[Aashna Narula](https://github.com/aashna94)|<strong>Lets Shapify</strong><br>Game done by observing and categorizing shapes based on their appearance and color.<br><sub>[GitHub](https://github.com/aashna94/shapify), [YouTube](https://youtu.be/INsfbSmFpyA). SpriteKit, UIKit.</sub>| Accepted |
|[Adann Simões](https://github.com/adannsergio)|<strong>Become the master of Dinumbers!</strong><br>Game helping kids in basic maths by practicing with dinosaurs.<br><sub>[GitHub](https://github.com/adannsergio/WWDC18). PlaygroundBooks, UIKit, CoreGraphics.</sub>| Submitted |
|...|...|...|...|...|
|[Sunghyun Cho](https://github.com/anaclumos)| <strong>Apple Pi</strong><br>Visual Playground to experience and learn several mathematical methods for calculating π.<br><sub>[GitHub](https://github.com/anaclumos/WWDC2018-Scholarship-Submission). UIKit, PlaygroundSupport. </sub>| Accepted |

This type of table will help future applicants to save hundreds of hours of time. Therefore, I suggest using this table format for future repositories (i.e., from 2019.) I would like to hear any thoughts on my idea.

Thank you for reading, and have a beautiful day :)

**Comment by Schemetrical** [comment]
Moving over to /2019 :), discussion is ongoing
